"""Centralized path definitions for the data analysis project."""


from pathlib import Path


# ============================================================================
# Project Root
# ============================================================================

# paths.py is in: data_analysis/src/data_analysis/system/utils/paths.py
# Need to go up 5 levels to reach: data_analysis/
_PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.parent
PROJECT_ROOT = _PROJECT_ROOT
"""Root directory of the data_analysis project."""

# ============================================================================
# Main Directories
# ============================================================================

SRC_DIR = PROJECT_ROOT / "src" / "data_analysis"
"""Main source directory."""

CORE_CONFIG_DIR = SRC_DIR / "crew" / "config"
"""CrewAI configuration directory."""

TEST_DATA_DIR = PROJECT_ROOT / "test_data"
"""Test data directory (for testing only)."""

# ============================================================================
# Analyses Directories
# ============================================================================

ANALYSES_DIR = PROJECT_ROOT / "analyses"
"""Main analyses directory."""

CURRENT_ANALYSIS_DIR = ANALYSES_DIR / "current_analysis"
"""Directory for the current/ongoing analysis."""

OUTPUT_AGENT_DIR = CURRENT_ANALYSIS_DIR / "agents"
"""Output directory for agent results (JSON files)."""

OUTPUT_SYSTEM_DIR = CURRENT_ANALYSIS_DIR / "system"
"""Output directory for system files."""

OUTPUT_SCRIPT_DIR = OUTPUT_SYSTEM_DIR / "script"
"""Output directory for script results."""

OUTPUT_EXECUTE_CODE_DIR = OUTPUT_SYSTEM_DIR / "executed_code"
"""Output directory for executed code results (pkl files and visualizations)."""

OUTPUT_DATA_DIR = CURRENT_ANALYSIS_DIR / "data"
"""Output directory for source data files (current analysis data)."""

# Legacy paths for backward compatibility (deprecated)
OUTPUT_AGENTS_DIR = OUTPUT_AGENT_DIR
OUTPUT_TOOLS_DIR = OUTPUT_SCRIPT_DIR
OUTPUT_RUNTIME_DIR = OUTPUT_EXECUTE_CODE_DIR

SAVED_ANALYSES_DIR = ANALYSES_DIR / "saved_analyses"
"""Directory for saved analyses."""

# ============================================================================
# UI Directories
# ============================================================================

UI_DIR = SRC_DIR / "ui"
"""User interface directory."""

UI_ASSETS_DIR = UI_DIR / "assets"
"""Assets directory."""

UI_ICONS_DIR = UI_ASSETS_DIR / "icons"
"""Icons directory."""

# ============================================================================
# Configuration Files
# ============================================================================

AGENTS_CONFIG_FILE = CORE_CONFIG_DIR / "agents.yaml"
"""Agents configuration file for CrewAI."""

TASKS_CONFIG_FILE = CORE_CONFIG_DIR / "tasks.yaml"
"""Tasks configuration file for CrewAI."""

# ============================================================================
# Runtime Files
# ============================================================================

ANALYSIS_STATUS_FILE = CURRENT_ANALYSIS_DIR / "analysis_status.json"
"""Analysis status tracking file (at root of current_analysis)."""

ERROR_FILE = OUTPUT_AGENT_DIR / "pipeline_error.json"
"""File storing pipeline execution errors (permanently stored in agents directory)."""

QUERY_RESULTS_PICKLE_FILE = OUTPUT_EXECUTE_CODE_DIR / "query_results.pkl"
"""Pickle file with executed query results."""

VISUALIZATION_RESULTS_PICKLE_FILE = OUTPUT_EXECUTE_CODE_DIR / "visualization_results.pkl"
"""Pickle file with executed visualization results."""

VISUALIZATION_IMAGES_DIR = OUTPUT_EXECUTE_CODE_DIR / "visualizations"
"""Directory for saved visualization images (PNG files)."""


def resolve_visualization_image_path(path_str: str) -> Path | None:
    """Resolve a stored visualization image path (relative or absolute) to an existing file.
    Supports paths saved as relative to PROJECT_ROOT (portable after clone) and legacy absolute paths.
    """
    if not path_str:
        return None
    p = Path(path_str)
    if p.is_absolute() and p.exists():
        return p
    # Relative path: resolve from project root (portable after git clone)
    resolved = PROJECT_ROOT / p
    if resolved.exists():
        return resolved
    # Legacy: absolute path from another machine — try same filename in current viz dir
    if p.is_absolute() and VISUALIZATION_IMAGES_DIR.exists():
        fallback = VISUALIZATION_IMAGES_DIR / p.name
        if fallback.exists():
            return fallback
    return None

# ============================================================================
# Script Output Files
# ============================================================================

RAW_SCHEMA_METADATA_FILE = OUTPUT_SCRIPT_DIR / "raw_metadata.json"
"""Raw schema metadata extracted by schema extractor."""

QUERY_ANALYSIS_FILE = OUTPUT_SCRIPT_DIR / "queries_analysis.json"
"""Query analysis generated by query analyzer."""

# ============================================================================
# Agent Output Files
# ============================================================================

ENRICHED_METADATA_FILE = OUTPUT_AGENT_DIR / "enriched_metadata.json"
"""Enriched metadata from schema interpreter agent."""

BUSINESS_ANALYSIS_FILE = OUTPUT_AGENT_DIR / "business_analysis.json"
"""Business analysis from business analyst agent."""

QUERIES_FILE = OUTPUT_AGENT_DIR / "queries.json"
"""Analysis queries from query builder agent."""

VISUALIZATIONS_FILE = OUTPUT_AGENT_DIR / "visualizations.json"
"""Visualizations from visualization designer agent."""

CONFIDENTIALITY_TEST_FILE = OUTPUT_AGENT_DIR / "confidentiality_test.json"
"""Confidentiality test from confidentiality tester agent."""

# ============================================================================
# Metadata File
# ============================================================================

METADATA_FILE = CURRENT_ANALYSIS_DIR / "metadata.json"
"""Metadata file for current analysis (at root of current_analysis)."""
